<?php

namespace WPMCP\Tools\WidgetBuilder\Compiler;

if (! defined('ABSPATH')) {
    exit;
}

/**
 * Manifest for compiled widgets (issue #72): the integrity record that decides
 * which generated PHP files the site is allowed to load.
 *
 * Two deliberate choices:
 *
 *  - The manifest lives in a WordPress OPTION, not in a file beside the code it
 *    vouches for. A hash record stored in the same directory as the files it
 *    hashes proves nothing: anyone who can write the sandbox can rewrite both.
 *    In the option, tampering with a generated file makes it stop loading.
 *  - The sandbox is wp-content/wpmcp-widgets, NOT uploads. Executable PHP does
 *    not belong under a media directory: it would be flagged (correctly) as
 *    critical by this plugin's own scanner, and uploads is the directory most
 *    likely to be world-readable and PHP-enabled. The directory still gets the
 *    same deny hardening the repo uses everywhere else (Export_Dir,
 *    Site_Backup_Dir): .htaccess, an index.php, and a README that spells out
 *    the nginx caveat, because .htaccess only covers Apache.
 *
 * Loading is manifest-only and hash-verified: a file on disk with no enabled,
 * hash-matching entry is inert. Disabling flips the entry without deleting the
 * spec or the file, so re-enable is instant and delete stays restorable from
 * the spec (the wpmcp_widget CPT remains the source of truth).
 */
class Compiled_Widget_Manifest
{
    public const OPTION   = 'wpmcp_compiled_widgets';
    public const DIR_NAME = 'wpmcp-widgets';

    public static function sandbox_dir(): string
    {
        /** Filter the directory compiled widget classes are written to. */
        return (string) apply_filters(
            'wpmcp_compiled_widgets_dir',
            trailingslashit(WP_CONTENT_DIR) . self::DIR_NAME
        );
    }

    /** Create the sandbox and block direct web access to it. */
    public static function protect(): bool
    {
        $dir = self::sandbox_dir();
        if (! wp_mkdir_p($dir)) {
            return false;
        }
        if (! is_file($dir . '/.htaccess')) {
            @file_put_contents($dir . '/.htaccess', "Require all denied\n");
        }
        if (! is_file($dir . '/index.php')) {
            @file_put_contents($dir . '/index.php', "<?php\n// Silence is golden.\n");
        }
        if (! is_file($dir . '/README.txt')) {
            @file_put_contents(
                $dir . '/README.txt',
                "WP MCP compiled widgets.\n\n"
                . "Every .php file here was generated by the plugin from a stored widget\n"
                . "spec, and is loaded only when its hash matches the wpmcp_compiled_widgets\n"
                . "option. Editing a file here does not change what runs; it stops the file\n"
                . "from loading at all.\n\n"
                . "The .htaccess here denies direct web access on Apache. If this site runs\n"
                . "nginx or another server that ignores .htaccess, deny this directory in the\n"
                . "server config as well.\n"
            );
        }
        return true;
    }

    /**
     * Every well-formed manifest entry, keyed by spec id.
     *
     * Entries are validated on the way out, not trusted: a stored 'file' must
     * be a plain basename that resolves inside the sandbox, so a tampered
     * option can never make the loader require() an arbitrary path.
     *
     * @return array<int,array{spec_id:int,name:string,class:string,file:string,hash:string,enabled:bool,compiled_at:string}>
     */
    public static function read(): array
    {
        $stored = get_option(self::OPTION, []);
        if (! is_array($stored)) {
            return [];
        }

        $out = [];
        foreach ($stored as $key => $entry) {
            $valid = self::validate_entry($key, $entry);
            if (null !== $valid) {
                $out[ $valid['spec_id'] ] = $valid;
            }
        }
        return $out;
    }

    /**
     * Validate one raw entry. Returns the normalized entry, or null when it is
     * malformed, mis-keyed, or points anywhere but at a plain file inside the
     * sandbox.
     *
     * @param mixed $key
     * @param mixed $entry
     * @return array{spec_id:int,name:string,class:string,file:string,hash:string,enabled:bool,compiled_at:string}|null
     */
    public static function validate_entry($key, $entry): ?array
    {
        if (! is_array($entry)) {
            return null;
        }
        $spec_id = isset($entry['spec_id']) ? (int) $entry['spec_id'] : 0;
        if ($spec_id <= 0 || (int) $key !== $spec_id) {
            return null;
        }

        $file = isset($entry['file']) && is_string($entry['file']) ? $entry['file'] : '';
        if ('' === $file || basename($file) !== $file || ! self::is_sandboxed($file)) {
            return null;
        }

        $class = isset($entry['class']) && is_string($entry['class']) ? $entry['class'] : '';
        if (1 !== preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $class)) {
            return null;
        }

        $hash = isset($entry['hash']) && is_string($entry['hash']) ? strtolower($entry['hash']) : '';
        if (1 !== preg_match('/^[0-9a-f]{64}$/', $hash)) {
            return null;
        }

        return [
            'spec_id'     => $spec_id,
            'name'        => isset($entry['name']) && is_string($entry['name']) ? $entry['name'] : '',
            'class'       => $class,
            'file'        => $file,
            'hash'        => $hash,
            'enabled'     => ! empty($entry['enabled']),
            'compiled_at' => isset($entry['compiled_at']) && is_string($entry['compiled_at']) ? $entry['compiled_at'] : '',
        ];
    }

    /** Absolute path of a sandbox file, or '' when it would escape the sandbox. */
    public static function path_for(string $file): string
    {
        if ('' === $file || basename($file) !== $file) {
            return '';
        }
        return trailingslashit(self::sandbox_dir()) . $file;
    }

    /**
     * Containment check that survives symlinks: the resolved path must sit
     * directly inside the resolved sandbox directory.
     */
    private static function is_sandboxed(string $file): bool
    {
        $dir = realpath(self::sandbox_dir());
        if (false === $dir) {
            // Sandbox not created yet: the basename check above is all we can
            // assert, and it already rules out traversal.
            return true;
        }
        $path = self::path_for($file);
        $real = realpath($path);
        if (false === $real) {
            return true; // Not written yet; nothing to contain.
        }
        return dirname($real) === rtrim($dir, '/\\');
    }

    /**
     * Replace the whole manifest. Entries are validated first, so an invalid
     * entry is rejected loudly instead of being stored and skipped later.
     *
     * @param array<int|string,array<string,mixed>> $entries
     * @return true|\WP_Error
     */
    public static function write(array $entries)
    {
        $clean = [];
        foreach ($entries as $key => $entry) {
            $valid = self::validate_entry($key, $entry);
            if (null === $valid) {
                return new \WP_Error('wpmcp_widget_manifest_invalid', 'Refusing to store a malformed compiled-widget manifest entry.');
            }
            $clean[ (string) $valid['spec_id'] ] = $valid;
        }

        update_option(self::OPTION, $clean, false);
        return true;
    }

    /**
     * Add or replace one entry, leaving the rest of the manifest alone.
     *
     * @param array<string,mixed> $entry
     * @return true|\WP_Error
     */
    public static function put(array $entry)
    {
        $entries = self::read();
        $spec_id = isset($entry['spec_id']) ? (int) $entry['spec_id'] : 0;
        $entries[ $spec_id ] = $entry;
        return self::write($entries);
    }

    public static function get(int $spec_id): ?array
    {
        $entries = self::read();
        return $entries[ $spec_id ] ?? null;
    }

    /**
     * Enable or disable one compiled widget without touching its spec or its
     * file. Disabled means "not loaded, not registered in the builder".
     *
     * This is a read-modify-write on the option, so two toggles racing each
     * other can lose one flip. It is not guarded with a lock because the worst
     * case is benign in both directions: the loser's widget stays in its
     * previous enable state, and a stale entry still cannot load anything the
     * hash check does not vouch for. A compile, which is the write that
     * actually matters, goes through Safe_Mutation and is snapshotted.
     */
    public static function set_enabled(int $spec_id, bool $enabled): bool
    {
        $entries = self::read();
        if (! isset($entries[ $spec_id ])) {
            return false;
        }
        $entries[ $spec_id ]['enabled'] = $enabled;
        return true === self::write($entries);
    }

    public static function remove(int $spec_id): bool
    {
        $entries = self::read();
        if (! isset($entries[ $spec_id ])) {
            return false;
        }
        unset($entries[ $spec_id ]);
        return true === self::write($entries);
    }

    /**
     * Load every enabled, hash-verified compiled widget file and return the
     * class names that are now defined.
     *
     * A file whose bytes no longer hash to the manifest's record is NOT
     * loaded: the only way to change what runs is to compile again through the
     * tool, which is the whole point of keeping the hashes in an option rather
     * than beside the code.
     *
     * @return array<int,string> spec_id => loaded class name
     */
    public static function load_enabled(): array
    {
        $loaded = [];
        foreach (self::read() as $spec_id => $entry) {
            if (! $entry['enabled']) {
                continue;
            }
            $path = self::path_for($entry['file']);
            if ('' === $path || ! is_file($path) || is_link($path)) {
                continue;
            }
            $bytes = @file_get_contents($path);
            if (! is_string($bytes) || ! hash_equals($entry['hash'], hash('sha256', $bytes))) {
                continue;
            }
            if (! class_exists($entry['class'], false)) {
                require_once $path;
            }
            if (class_exists($entry['class'], false)) {
                $loaded[ $spec_id ] = $entry['class'];
            }
        }
        return $loaded;
    }

    /** Spec ids that currently have an enabled, hash-matching compiled class. */
    public static function enabled_spec_ids(): array
    {
        $ids = [];
        foreach (self::read() as $spec_id => $entry) {
            if ($entry['enabled']) {
                $ids[] = (int) $spec_id;
            }
        }
        return $ids;
    }
}
