<?php

namespace WPMCP\Tools\Media;

if (! defined('ABSPATH')) {
    exit;
}

/**
 * sideload-image: add a new image attachment, either fetched from a url the
 * caller names (core's media_sideload_image()) or, with a prompt (issue
 * #456), generated through WordPress core's AI client (wp_ai_client_prompt(),
 * WordPress 7.0+) with whatever provider the site owner configured under
 * Settings > Connectors. wpmcp holds no provider key and picks no provider:
 * when AI is disabled, or no configured provider has an image model, the
 * call is refused before the prompt leaves the site.
 *
 * Generated bytes go through Remote_Image_Guard::insert() (size cap, real
 * image check, sanitized name); a provider that answers with a url instead
 * of bytes is fetched only through the guarded download (https, public
 * host, no redirects, size caps). The prompt, provider and model are kept as
 * attachment meta. Pure creation, so not Safe_Mutation-wrapped: either mode
 * records a 'media_import' snapshot, and rolling the operation back deletes
 * the attachment and its files.
 */
class Sideload_Image
{
    public const META_PROMPT   = '_wpmcp_ai_prompt';
    public const META_PROVIDER = '_wpmcp_ai_provider';
    public const META_MODEL    = '_wpmcp_ai_model';

    private const MAX_PROMPT_CHARS = 4000;

    /** @var callable|null (string $prompt): prompt builder; null means core's wp_ai_client_prompt(). */
    private $prompt_builder;

    /**
     * @param callable|null $prompt_builder Seam for tests: returns an object
     *        with the WP_AI_Client_Prompt_Builder methods this tool calls.
     */
    public function __construct(?callable $prompt_builder = null)
    {
        $this->prompt_builder = $prompt_builder;
    }

    public function handle(array $args): array
    {
        $url    = trim((string) ($args['url'] ?? ''));
        $prompt = trim((string) ($args['prompt'] ?? ''));
        if ('' !== $url && '' !== $prompt) {
            throw new \InvalidArgumentException('Pass either "url" or "prompt", not both.');
        }
        if ('' === $url && '' === $prompt) {
            throw new \InvalidArgumentException('A "url" or a "prompt" is required.');
        }

        $ai       = null;
        $media_id = '' !== $prompt ? $this->generate($prompt, $args, $ai) : $this->from_url($url, $args);

        if (array_key_exists('alt', $args)) {
            update_post_meta($media_id, '_wp_attachment_image_alt', wp_slash(sanitize_text_field((string) $args['alt'])));
        }

        $out = [
            'operation_id' => Media_Import_Snapshot::record(
                'sideload-image',
                $media_id,
                $args,
                (string) ($args['session_id'] ?? 'default')
            ),
            'media_id'     => $media_id,
            'url'          => (string) wp_get_attachment_url($media_id),
        ];

        return null !== $ai ? $out + $ai : $out;
    }

    private function from_url(string $url, array $args): int
    {
        if (! function_exists('media_sideload_image')) {
            require_once ABSPATH . 'wp-admin/includes/media.php';
            require_once ABSPATH . 'wp-admin/includes/file.php';
            require_once ABSPATH . 'wp-admin/includes/image.php';
        }

        $post_id     = (int) ($args['post_id'] ?? 0);
        $description = isset($args['description']) ? (string) $args['description'] : null;

        $media_id = media_sideload_image($url, $post_id, $description, 'id');
        if (is_wp_error($media_id)) {
            throw new \InvalidArgumentException(esc_html($media_id->get_error_message()));
        }

        return (int) $media_id;
    }

    /**
     * @param array{provider: string, model: string}|null $ai set to the provider and model used.
     */
    private function generate(string $prompt, array $args, ?array &$ai): int
    {
        if (mb_strlen($prompt) > self::MAX_PROMPT_CHARS) {
            throw new \InvalidArgumentException(sprintf('The "prompt" is longer than %d characters.', (int) self::MAX_PROMPT_CHARS));
        }
        $ratio = trim((string) ($args['ratio'] ?? ''));
        if ('' !== $ratio && 1 !== preg_match('/^[1-9]\d{0,2}:[1-9]\d{0,2}$/', $ratio)) {
            throw new \InvalidArgumentException('The "ratio" must be width:height, for example 16:9.');
        }

        if (null === $this->prompt_builder && ! function_exists('wp_ai_client_prompt')) {
            throw new \RuntimeException('Generating images needs the AI client in WordPress 7.0 or later; this site has none.');
        }
        if (function_exists('wp_supports_ai') && ! wp_supports_ai()) {
            throw new \RuntimeException('AI features are disabled on this site (wp_supports_ai), so no image was generated and the prompt was not sent.');
        }

        $builder = $this->builder($prompt, $ratio);
        if (true !== $builder->is_supported_for_image_generation()) {
            if ('' !== $ratio && true === $this->builder($prompt, '')->is_supported_for_image_generation()) {
                throw new \RuntimeException(sprintf('The image model configured on this site does not support ratio %s; retry without "ratio" or with another one.', esc_html($ratio)));
            }
            throw new \RuntimeException('No AI provider configured on this site can generate images, so the prompt was not sent. An administrator can connect one with an image model under Settings > Connectors.');
        }

        $result = $builder->generate_image_result();
        if (is_wp_error($result)) {
            throw new \RuntimeException('The AI provider could not generate the image: ' . esc_html($result->get_error_message()));
        }

        try {
            $file     = $result->toImageFile();
            $provider = sanitize_key((string) $result->getProviderMetadata()->getId());
            $model    = sanitize_text_field((string) $result->getModelMetadata()->getId());
        } catch (\Throwable $e) {
            throw new \RuntimeException('The AI provider returned no image: ' . esc_html($e->getMessage()));
        }

        $tmp = $this->to_temp_file($file);

        $title = trim((string) ($args['description'] ?? ''));
        if ('' === $title) {
            $title = wp_trim_words($prompt, 12, '');
        }
        $slug = substr(sanitize_title($prompt), 0, 60);
        $ext  = function_exists('wp_get_default_extension_for_mime_type')
            ? (string) wp_get_default_extension_for_mime_type((string) $file->getMimeType())
            : '';

        $media_id = Remote_Image_Guard::insert(
            $tmp,
            'ai-' . ('' !== $slug ? $slug : 'image') . '.' . ('' !== $ext ? $ext : 'png'),
            (int) ($args['post_id'] ?? 0),
            ['post_title' => sanitize_text_field($title)]
        );

        update_post_meta($media_id, self::META_PROMPT, wp_slash(sanitize_textarea_field($prompt)));
        update_post_meta($media_id, self::META_PROVIDER, wp_slash($provider));
        update_post_meta($media_id, self::META_MODEL, wp_slash($model));

        $ai = ['provider' => $provider, 'model' => $model];
        return $media_id;
    }

    /** @return object the WP_AI_Client_Prompt_Builder (or the injected stand-in). */
    private function builder(string $prompt, string $ratio): object
    {
        $builder = null !== $this->prompt_builder
            ? ($this->prompt_builder)($prompt)
            : wp_ai_client_prompt($prompt);

        if ('' !== $ratio) {
            $builder = $builder->as_output_media_aspect_ratio($ratio);
        }

        return $builder;
    }

    /**
     * The generated image as a temp file: inline base64 decoded under the
     * media byte cap, or a provider url fetched through the guarded download.
     *
     * @param object $file the AI client's File DTO.
     */
    private function to_temp_file(object $file): string
    {
        if (! function_exists('wp_tempnam')) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }

        if ($file->isRemote()) {
            $url  = (string) $file->getUrl();
            $host = (string) wp_parse_url($url, PHP_URL_HOST);
            Remote_Image_Guard::validate_url($url, [$host]);
            Remote_Image_Guard::assert_public_host($host);
            return Remote_Image_Guard::download($url);
        }

        $data = (string) preg_replace('/\s+/', '', (string) $file->getBase64Data());
        $max  = Remote_Image_Guard::max_bytes();
        if (intdiv(strlen($data) * 3, 4) - substr_count(substr($data, -2), '=') > $max) {
            throw new \RuntimeException(sprintf('The generated image is above the %d byte limit.', (int) $max));
        }
        // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_decode -- strict decode of the image bytes the site's AI provider returned; written to disk as data and verified as an image, never executed.
        $bytes = base64_decode($data, true);
        if (false === $bytes || '' === $bytes) {
            throw new \RuntimeException('The AI provider returned no usable image data.');
        }

        $tmp = wp_tempnam('wpmcp-ai-image');
        if (false === file_put_contents($tmp, $bytes)) {
            wp_delete_file($tmp);
            throw new \RuntimeException('The generated image could not be written to a temporary file.');
        }

        return $tmp;
    }
}
