<?php

namespace WPMCP\Integrations;

use WPMCP\Tools\Filesystem\Filesystem_Guard;

if (! defined('ABSPATH')) {
    exit;
}

/**
 * The create-child-theme operation of the theme integration (issue #69,
 * phase 2 on top of the #144 theme-read/theme-write pair).
 *
 * A confirm-gated, path-confined, idempotent scaffolder that refuses to create
 * a grandchild. It is snapshot-first like every other write: the dispatcher
 * captures a theme_scaffold snapshot (Safety\Snapshot) of the target directory
 * through Safe_Mutation before a byte is written, so rollback-operation
 * removes the scaffold again (Safety\Rollback_Service).
 *
 * Kept out of Theme_Integration so the pair's context and theme-mod code and
 * this file-writing code can be reviewed, and later extended, separately.
 */
final class Child_Theme_Scaffolder
{
    /** Comment written into a scaffolded style.css so re-runs recognize their own work. */
    private const SCAFFOLD_MARKER = 'Generated by WPMCP create-child-theme';

    /**
     * The dispatcher operation definition for create-child-theme.
     *
     * @return array<string,mixed>
     */
    public static function operation(): array
    {
        return [
            'mode'               => 'destructive',
            // edit_themes is WordPress's own gate for putting PHP into the
            // themes directory; Filesystem_Guard adds edit_files and
            // DISALLOW_FILE_EDIT on top, in validate().
            'capability'         => 'edit_themes',
            'enabled_by_default' => (bool) apply_filters('wpmcp_enable_theme_write', false),
            'description'        => 'Scaffold a child theme (style.css + functions.php enqueueing the parent stylesheet) of the active theme, or of an explicit installed parent. Idempotent: re-running against an existing wpmcp-scaffolded child completes or reports it instead of failing. Refuses to build a child of a child (no grandchildren). Requires confirm:true, the edit_themes capability, file editing to be allowed on the site, and the wpmcp_enable_theme_write opt-in. Snapshotted before any file is written; rollback-operation removes the scaffold again (unless it has since been activated). Does not activate the child theme',
            'input_schema'       => [
                'type'       => 'object',
                'properties' => [
                    'slug'   => [ 'type' => 'string', 'description' => 'Directory slug for the child theme; defaults to {parent}-child. Sanitized to a safe key, confined to the themes directory' ],
                    'name'   => [ 'type' => 'string', 'description' => 'Human-readable theme Name header; defaults to "{Parent Name} Child"' ],
                    'parent' => [ 'type' => 'string', 'description' => 'Stylesheet directory of an installed parent theme; defaults to the active theme\'s template. Must not itself be a child theme' ],
                ],
            ],
            'validate'           => static fn (array $args): ?array => self::plan_scaffold($args)['error'] ?? null,
            // Snapshot-first like every other write: the scaffold directory's
            // prior state is captured before a byte is written, so the
            // creation is undoable through rollback-operation. A re-run
            // against a complete scaffold writes nothing and therefore burns
            // no rollback slot.
            'snapshot'           => static function (array $args): ?array {
                $plan = self::plan_scaffold($args);
                if (isset($plan['error']) || true === $plan['existing']) {
                    return null;
                }
                return [ 'object_type' => 'theme_scaffold', 'object_id' => (string) $plan['slug'] ];
            },
            'handler'            => static function (array $args): array {
                $plan = self::plan_scaffold($args);
                if (isset($plan['error'])) {
                    $error = $plan['error'];
                    // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped -- surfaced as a JSON tool error by Integration_Dispatcher, never rendered as HTML.
                    throw new Operation_Refused((string) $error['code'], (string) $error['message'], (array) ($error['data'] ?? []));
                }
                return self::write_scaffold($plan);
            },
        ];
    }

    /**
     * Resolve and vet everything the scaffolder needs from the args, with no
     * side effects, so both validate() and the handler agree on the outcome.
     *
     * @param  array<string,mixed> $args
     * @return array<string,mixed> ['error' => [...]] or the resolved plan.
     */
    private static function plan_scaffold(array $args): array
    {
        $refuse = static fn (string $code, string $message, array $data = []): array
            => [ 'error' => [ 'code' => $code, 'message' => $message, 'data' => $data ] ];

        $gate = self::file_writes_allowed();
        if (is_wp_error($gate)) {
            return $refuse((string) $gate->get_error_code(), (string) $gate->get_error_message());
        }

        // Parent: the active template by default, or an explicitly named
        // installed theme. Refuse only when the chosen parent is ITSELF a
        // child, which is the actual grandchild condition; hard-refusing
        // whenever any child is active would brick the tool the moment the
        // user activates the child they just made.
        // A theme directory name, not a key: sanitize_key() would lowercase
        // "Divi" and then miss it on a case-sensitive filesystem. Anything
        // outside [A-Za-z0-9_-] (a slash, a dot) cannot name an installed
        // theme and is refused as unknown before it reaches wp_get_theme().
        $requested = (string) ($args['parent'] ?? '');
        if ('' !== $requested) {
            $candidate = 1 === preg_match('/^[A-Za-z0-9_-]{1,100}$/', $requested) ? wp_get_theme($requested) : null;
            if (null === $candidate || ! $candidate->exists()) {
                return $refuse('unknown_parent', sprintf('No installed theme with stylesheet "%s".', $requested), [ 'parent' => $requested ]);
            }
            if ($candidate->parent()) {
                return $refuse('grandchild_refused', sprintf('Theme "%s" is itself a child theme; creating a grandchild theme is not supported.', $requested), [ 'parent' => $requested ]);
            }
            $parent_slug = $requested;
        } else {
            if (is_child_theme()) {
                return $refuse(
                    'grandchild_refused',
                    'The active theme is already a child theme; creating a grandchild theme is not supported. Pass an explicit parent to scaffold a child of a different installed parent theme.',
                    [ 'stylesheet' => get_stylesheet(), 'template' => get_template() ]
                );
            }
            $parent_slug = get_template();
        }

        $slug = sanitize_key((string) ($args['slug'] ?? ($parent_slug . '-child')));
        // Compared case-insensitively: on a case-insensitive filesystem
        // "divi-x" and "Divi-X" are the same directory.
        if ('' === $slug || strtolower($slug) === strtolower($parent_slug)) {
            return $refuse('invalid_slug', 'Child theme slug is empty or collides with the parent theme slug after sanitization.', [ 'slug' => $slug ]);
        }

        // Path confinement: sanitize_key() already leaves a single token with
        // no slashes or dots, and resolve_path() re-proves the result cannot
        // leave the theme root (symlinked leaf included).
        $root = get_theme_root();
        $dir  = Filesystem_Guard::resolve_path($slug, $root);
        if (is_wp_error($dir)) {
            return $refuse('invalid_slug', (string) $dir->get_error_message(), [ 'slug' => $slug ]);
        }

        $existing = false;
        if (is_dir($dir)) {
            $style = is_file($dir . '/style.css') && ! is_link($dir . '/style.css') ? file_get_contents($dir . '/style.css') : false;
            if (! is_string($style) || false === strpos($style, self::SCAFFOLD_MARKER)) {
                return $refuse('directory_exists', sprintf('Theme directory "%s" already exists and was not scaffolded by wpmcp; refusing to touch it.', $slug), [ 'slug' => $slug ]);
            }
            $theme = wp_get_theme($slug);
            if ($theme->exists() && $theme->get('Template') !== $parent_slug) {
                return $refuse(
                    'parent_mismatch',
                    sprintf('Existing scaffold "%s" is a child of "%s", not of "%s".', $slug, (string) $theme->get('Template'), $parent_slug),
                    [ 'slug' => $slug, 'template' => (string) $theme->get('Template'), 'expected' => $parent_slug ]
                );
            }
            // A marker-bearing directory is only "already done" when BOTH
            // files are there; a half-written scaffold is completed instead
            // of being reported as an activatable theme.
            $existing = is_file($dir . '/functions.php') && is_file($dir . '/style.css');
        }

        $parent = wp_get_theme($parent_slug);
        $name   = trim((string) ($args['name'] ?? '')) !== ''
            ? (string) $args['name']
            : $parent->get('Name') . ' Child';

        return [
            'slug'        => $slug,
            'dir'         => $dir,
            'parent'      => $parent_slug,
            'parent_name' => (string) $parent->get('Name'),
            'name'        => $name,
            'existing'    => $existing,
        ];
    }

    /**
     * Perform the vetted scaffold. functions.php is written FIRST and the
     * marker-bearing style.css LAST, and a failure removes whatever was
     * created, so a partial write can never leave a marker that makes later
     * runs report a half-theme as done.
     *
     * @param  array<string,mixed> $plan
     * @return array<string,mixed>
     */
    private static function write_scaffold(array $plan): array
    {
        $dir = (string) $plan['dir'];

        if (true === $plan['existing']) {
            return [
                'created'    => false,
                'existing'   => true,
                'stylesheet' => $plan['slug'],
                'template'   => $plan['parent'],
                'path'       => $dir,
            ];
        }

        $fresh = ! is_dir($dir);
        if ($fresh && ! wp_mkdir_p($dir)) {
            // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped -- surfaced as a JSON tool error by Integration_Dispatcher, never rendered as HTML.
            throw new Operation_Refused('mkdir_failed', 'Could not create the child theme directory.', [ 'path' => $dir ]);
        }

        $functions = "<?php\n"
            . '// ' . self::SCAFFOLD_MARKER . ".\n"
            . "add_action('wp_enqueue_scripts', function () {\n"
            . "    wp_enqueue_style('wpmcp-child-parent-style', get_template_directory_uri() . '/style.css', [], wp_get_theme(get_template())->get('Version'));\n"
            . "});\n";

        $style = "/*\n"
            . 'Theme Name: ' . self::css_comment_safe((string) $plan['name']) . "\n"
            . 'Template: ' . $plan['parent'] . "\n"
            . 'Version: 1.0.0' . "\n"
            . 'Description: Child theme of ' . self::css_comment_safe((string) $plan['parent_name']) . '. ' . self::SCAFFOLD_MARKER . ".\n"
            . "*/\n";

        // functions.php first, style.css (the idempotency marker) last.
        $fs = self::filesystem();
        if (
            ! $fs->put_contents($dir . '/functions.php', $functions, 0644)
            || ! $fs->put_contents($dir . '/style.css', $style, 0644)
        ) {
            self::clean_partial_scaffold($dir, $fresh);
            // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped -- surfaced as a JSON tool error by Integration_Dispatcher, never rendered as HTML.
            throw new Operation_Refused('write_failed', 'Could not write the child theme files; the partial scaffold was removed.', [ 'path' => $dir ]);
        }

        // Without this the new directory is absent from the cached
        // theme_roots transient and wp_get_themes(), so the child does not
        // show up under Appearance -> Themes and is not activatable.
        wp_clean_themes_cache();

        Filesystem_Guard::log('create-child-theme', Filesystem_Guard::to_relative($dir));

        return [
            'created'    => true,
            'existing'   => false,
            'stylesheet' => $plan['slug'],
            'name'       => $plan['name'],
            'template'   => $plan['parent'],
            'path'       => $dir,
            'activated'  => false,
        ];
    }

    /**
     * Remove a failed scaffold's files, and the directory itself when we
     * made it. Plugin Check promotes WordPress.WP.AlternativeFunctions to an
     * error, so deletion goes through WP_Filesystem
     * rather than unlink() and rmdir(), the same way File_Backup does.
     */
    private static function clean_partial_scaffold(string $dir, bool $created_dir): void
    {
        foreach ([ 'style.css', 'functions.php' ] as $file) {
            if (is_file($dir . '/' . $file)) {
                self::filesystem()->delete($dir . '/' . $file);
            }
        }
        if ($created_dir && is_dir($dir)) {
            self::filesystem()->rmdir($dir);
        }
    }

    /**
     * A direct-method WP_Filesystem. Plugin Check promotes
     * WordPress.WP.AlternativeFunctions to an error, so the scaffold's writes
     * and cleanup go through WP_Filesystem rather than file_put_contents()
     * and rmdir(). The direct transport is instantiated explicitly: a tool
     * call cannot prompt for FTP credentials, and WP_Filesystem() silently
     * leaves the global unset when it picks a transport that needs them.
     */
    private static function filesystem(): \WP_Filesystem_Direct
    {
        require_once ABSPATH . 'wp-admin/includes/class-wp-filesystem-base.php';
        require_once ABSPATH . 'wp-admin/includes/class-wp-filesystem-direct.php';
        return new \WP_Filesystem_Direct(null);
    }

    /**
     * Gate file creation the way every other write path in the repo does:
     * edit_files plus DISALLOW_FILE_EDIT. The extra filter exists so tests
     * (and a site that wants a harder no) can force the refusal without
     * redefining a constant.
     *
     * @return true|\WP_Error
     */
    private static function file_writes_allowed()
    {
        /** Filter: force theme file writes off without defining DISALLOW_FILE_EDIT. */
        if ((bool) apply_filters('wpmcp_theme_file_edit_disallowed', false)) {
            return new \WP_Error('file_edit_disabled', 'File editing is disabled on this site.');
        }
        return Filesystem_Guard::writes_allowed();
    }

    /**
     * Make a caller-supplied string safe inside a /* ... *&#47; block: no
     * newlines (which would forge extra theme headers) and no comment
     * terminator (which would end the block and append attacker CSS to a
     * stylesheet served to every visitor).
     */
    private static function css_comment_safe(string $value): string
    {
        $value = str_replace([ "\r", "\n", '*/', '/*' ], ' ', $value);
        $value = trim(preg_replace('/\s+/', ' ', $value) ?? '');
        return '' === $value ? 'Child Theme' : mb_substr($value, 0, 120);
    }
}
