<?php

namespace WPMCP\Integrations;

use WPMCP\Tools\Filesystem\Filesystem_Guard;

if (! defined('ABSPATH')) {
    exit;
}

/**
 * Theme integration (wpmcp/theme-read + theme-write), issue #69.
 *
 * Four core operations plus per-family framework packs:
 *  - get-context / list-theme-mods (read)
 *  - set-theme-mods (write): allowlisted KEYS with a per-key VALUE sanitizer,
 *    snapshotted on theme_mods_{stylesheet} and reversible via
 *    rollback-operation
 *  - create-child-theme (destructive): confirm-gated, path-confined,
 *    idempotent scaffolder that refuses to create a grandchild
 *  - framework_pack_operations(): family-conditional settings pack, registered
 *    only while that theme family is active
 *
 * Safety posture, after adversarial review:
 *  - both write ops are DEFAULT-OFF behind the wpmcp_enable_theme_write filter,
 *    matching the Meta Box / ACF write ops
 *  - theme-mod ops require edit_theme_options, WordPress's own gate for theme
 *    options (and the capability Assign_Menu_To_Location already uses to touch
 *    this very option); the scaffolder requires edit_themes on top of that and
 *    additionally honors DISALLOW_FILE_EDIT via Filesystem_Guard
 *  - every refusal that can be decided from the args is expressed in the op's
 *    'validate' callable, so it returns the dispatcher's top-level error
 *    envelope and burns no snapshot row; mid-write failures throw
 *    Operation_Refused for the same envelope
 *  - the scaffold directory is confined to get_theme_root() through
 *    Filesystem_Guard::resolve_path() and audited through Filesystem_Guard::log()
 *
 * Always available: WordPress always has an active theme, so is_available()
 * is unconditionally true (unlike host-plugin integrations).
 */
class Theme_Integration extends Integration_Dispatcher
{
    /** Comment written into a scaffolded style.css so re-runs recognize their own work. */
    private const SCAFFOLD_MARKER = 'Generated by WPMCP create-child-theme';

    /**
     * Parent-theme slugs (and slug prefixes) mapped to a framework family
     * label for get-context. Matched case-insensitively, because Divi and
     * Avada ship directories with a capital letter. Extend via the
     * wpmcp_theme_framework_map filter.
     *
     * @var array<string,string>
     */
    private const FRAMEWORK_MAP = [
        'genesis'          => 'genesis',
        'astra'            => 'astra',
        'generatepress'    => 'generatepress',
        'oceanwp'          => 'oceanwp',
        'kadence'          => 'kadence',
        'blocksy'          => 'blocksy',
        'divi'             => 'divi',
        'avada'            => 'avada',
        'hello-elementor'  => 'hello-elementor',
        'neve'             => 'neve',
        'twentytwentysix'  => 'core-default',
        'twentytwentyfive' => 'core-default',
        'twentytwentyfour' => 'core-default',
    ];

    /**
     * Theme-mod keys the write op may touch, each with the sanitizer its
     * value must survive. Presentation-level knobs only; anything structural
     * (menu assignments, widget areas, custom CSS post linkage) is refused
     * even if a caller asks nicely.
     *
     * set_theme_mod() bypasses the Customizer's sanitize_callback entirely,
     * so these sanitizers are the ONLY thing standing between a caller and,
     * for example, background_color being echoed unescaped inside core's
     * _custom_background_cb() <style> block.
     *
     * Keys deliberately absent: site_icon (an option, not a theme mod) and
     * header_text (encoded as header_textcolor === 'blank'); writing either
     * as a mod is a silent no-op.
     *
     * @var array<string,string>
     */
    private const MOD_SANITIZERS = [
        'custom_logo'           => 'attachment_id',
        'header_image'          => 'header_image',
        'header_textcolor'      => 'hex_or_blank',
        'background_color'      => 'hex',
        'background_image'      => 'url',
        'background_preset'     => 'preset',
        'background_position_x' => 'position_x',
        'background_position_y' => 'position_y',
        'background_size'       => 'size',
        'background_repeat'     => 'repeat',
        'background_attachment' => 'attachment',
    ];

    /** @var array<string,array<int,string>> enum vocabularies for the background mods. */
    private const MOD_ENUMS = [
        'preset'     => [ 'default', 'fill', 'fit', 'repeat', 'custom' ],
        'position_x' => [ 'left', 'center', 'right' ],
        'position_y' => [ 'top', 'center', 'bottom' ],
        'size'       => [ 'auto', 'contain', 'cover' ],
        'repeat'     => [ 'repeat-x', 'repeat-y', 'repeat', 'no-repeat' ],
        'attachment' => [ 'fixed', 'scroll' ],
    ];

    /**
     * Structural keys refused outright with a dedicated error so callers see
     * "refused", not "not on the allowlist" (they must never be filterable
     * onto the allowlist either).
     *
     * @var array<int,string>
     */
    private const MOD_STRUCTURAL = [
        'nav_menu_locations',
        'sidebars_widgets',
        'custom_css_post_id',
    ];

    /**
     * Astra option keys the framework pack may write, with their sanitizer.
     * Narrow on purpose: colors and content width, the knobs an agent is
     * actually asked for. Widen with wpmcp_theme_framework_pack_allowlist.
     *
     * @var array<string,string>
     */
    private const ASTRA_SETTINGS = [
        'theme-color'        => 'color',
        'link-color'         => 'color',
        'link-h-color'       => 'color',
        'text-color'         => 'color',
        'heading-base-color' => 'color',
        'site-content-width' => 'width',
    ];

    public function integration(): string
    {
        return 'theme';
    }

    public function is_available(): bool
    {
        return true;
    }

    protected function summary(): string
    {
        return 'Active theme (context detection, allowlisted theme mods, child-theme scaffolding)';
    }

    protected function operations(): array
    {
        return array_merge(
            [
                'get-context'        => $this->op_get_context(),
                'list-theme-mods'    => $this->op_list_theme_mods(),
                'set-theme-mods'     => $this->op_set_theme_mods(),
                'create-child-theme' => $this->op_create_child_theme(),
            ],
            $this->framework_pack_operations()
        );
    }

    /**
     * Curated framework settings packs (issue #69, third bullet). A pack's
     * ops are only in the catalog while its theme family is the active one,
     * so an Astra-only op is never advertised on a Genesis site, and its
     * writes refresh that framework's CSS cache.
     *
     * @return array<string,array<string,mixed>>
     */
    protected function framework_pack_operations(): array
    {
        if ('astra' !== self::detect_framework()) {
            return [];
        }
        return $this->astra_pack();
    }

    /** Whether the theme write ops are opted in on this site (default off). */
    private static function writes_enabled(): bool
    {
        /** Filter: opt the theme write ops in. Default off, like the ACF/Meta Box write ops. */
        return (bool) apply_filters('wpmcp_enable_theme_write', false);
    }

    /** @return array<string,mixed> */
    private function op_get_context(): array
    {
        return [
            'mode'         => 'read',
            'description'  => 'Report the active theme context: name, version, framework family, parent/child relationship, block-theme flag, registered nav menus, and declared theme supports',
            'input_schema' => [ 'type' => 'object', 'properties' => [] ],
            'handler'      => function (): array {
                $theme  = wp_get_theme();
                $parent = $theme->parent();

                $supports = [];
                foreach ([ 'custom-logo', 'custom-header', 'custom-background', 'post-thumbnails', 'editor-styles', 'wp-block-styles', 'align-wide', 'title-tag', 'html5', 'automatic-feed-links' ] as $feature) {
                    if (current_theme_supports($feature)) {
                        $supports[] = $feature;
                    }
                }

                return [
                    'stylesheet'     => get_stylesheet(),
                    'template'       => get_template(),
                    'name'           => $theme->get('Name'),
                    'version'        => $theme->get('Version'),
                    'is_child_theme' => is_child_theme(),
                    'parent'         => $parent ? [
                        'stylesheet' => $parent->get_stylesheet(),
                        'name'       => $parent->get('Name'),
                        'version'    => $parent->get('Version'),
                    ] : null,
                    'is_block_theme' => wp_is_block_theme(),
                    'framework'      => self::detect_framework(),
                    'nav_menus'      => (array) get_registered_nav_menus(),
                    'supports'       => $supports,
                ];
            },
        ];
    }

    /** @return array<string,mixed> */
    private function op_list_theme_mods(): array
    {
        return [
            'mode'         => 'read',
            // Raw mod values include nav_menu_locations and sidebars_widgets,
            // i.e. the site's menu and widget wiring, so this read sits at the
            // same capability as the write half rather than at edit_posts.
            'capability'   => 'edit_theme_options',
            'description'  => 'List the active theme\'s theme mods with per-key writability: allowlisted (writable via set-theme-mods), structural (always refused), or other (not writable through this tool)',
            'input_schema' => [ 'type' => 'object', 'properties' => [] ],
            'handler'      => function (): array {
                $allowlist = self::allowlist();
                $mods      = [];
                foreach ((array) get_theme_mods() as $key => $value) {
                    $key    = (string) $key;
                    $mods[] = [
                        'key'      => $key,
                        'value'    => $value,
                        'writable' => in_array($key, $allowlist, true) ? 'allowlisted'
                            : (in_array($key, self::MOD_STRUCTURAL, true) ? 'structural' : 'other'),
                    ];
                }
                return [ 'stylesheet' => get_stylesheet(), 'mods' => $mods, 'allowlist' => $allowlist ];
            },
        ];
    }

    /** @return array<string,mixed> */
    private function op_set_theme_mods(): array
    {
        return [
            'mode'               => 'write',
            'capability'         => 'edit_theme_options',
            'enabled_by_default' => self::writes_enabled(),
            'description'        => 'Set one or more allowlisted theme mods on the active theme. Values are sanitized per key (hex colors, attachment ids, URLs, enums) because set_theme_mod() bypasses the Customizer sanitizers. Structural keys (nav_menu_locations, sidebars_widgets, custom_css_post_id) are refused; any non-allowlisted key or unsanitizable value rejects the whole call before any write. Snapshotted on the theme_mods option; restorable with rollback-operation',
            'input_schema'       => [
                'type'       => 'object',
                'properties' => [
                    'mods' => [
                        'type'                 => 'object',
                        'minProperties'        => 1,
                        // Scalars only: an array reaching set_theme_mod() for a
                        // presentation key breaks front-end rendering.
                        'additionalProperties' => [ 'type' => [ 'string', 'integer', 'number', 'boolean' ] ],
                    ],
                ],
                'required'   => [ 'mods' ],
            ],
            // Whole-batch validation BEFORE the dispatcher snapshots anything:
            // one bad key or value rejects the call with no side effects and
            // no burned rollback slot.
            'validate'           => static function (array $args): ?array {
                $allowlist = self::allowlist();
                foreach ((array) ($args['mods'] ?? []) as $key => $value) {
                    $key = (string) $key;
                    if (in_array($key, self::MOD_STRUCTURAL, true)) {
                        return [
                            'code'    => 'structural_key_refused',
                            'message' => sprintf('Theme mod "%s" is structural and can never be written through this tool.', $key),
                            'data'    => [ 'key' => $key ],
                        ];
                    }
                    if (! in_array($key, $allowlist, true)) {
                        return [
                            'code'    => 'key_not_allowlisted',
                            'message' => sprintf('Theme mod "%s" is not on the write allowlist.', $key),
                            'data'    => [ 'key' => $key, 'allowlist' => $allowlist ],
                        ];
                    }
                    if (null === self::sanitize_mod($key, $value)) {
                        return [
                            'code'    => 'invalid_mod_value',
                            'message' => sprintf('Value for theme mod "%s" is not valid for that key.', $key),
                            'data'    => [ 'key' => $key ],
                        ];
                    }
                }
                return null;
            },
            'handler'            => static function (array $args): array {
                $out = [];
                foreach ((array) $args['mods'] as $key => $value) {
                    $key   = (string) $key;
                    $clean = self::sanitize_mod($key, $value);
                    if (null === $clean) {
                        // Unreachable via dispatch (validate ran first); kept
                        // so a direct handler call cannot write a raw value.
                        throw new Operation_Refused('invalid_mod_value', sprintf('Value for theme mod "%s" is not valid.', $key), [ 'key' => $key ]);
                    }
                    set_theme_mod($key, $clean);
                    $out[ $key ] = get_theme_mod($key);
                }
                return [ 'stylesheet' => get_stylesheet(), 'mods' => $out ];
            },
            'snapshot'           => static fn (array $args) => [
                'object_type' => 'option',
                'object_id'   => 'theme_mods_' . get_stylesheet(),
            ],
        ];
    }

    /** @return array<string,mixed> */
    private function op_create_child_theme(): array
    {
        return [
            'mode'               => 'destructive',
            // edit_themes is WordPress's own gate for putting PHP into the
            // themes directory; Filesystem_Guard adds edit_files and
            // DISALLOW_FILE_EDIT on top, in validate().
            'capability'         => 'edit_themes',
            'enabled_by_default' => self::writes_enabled(),
            'description'        => 'Scaffold a child theme (style.css + functions.php enqueueing the parent stylesheet) of the active theme, or of an explicit installed parent. Idempotent: re-running against an existing wpmcp-scaffolded child completes or reports it instead of failing. Refuses to build a child of a child (no grandchildren). Requires confirm:true, the edit_themes capability, file editing to be allowed on the site, and the wpmcp_enable_theme_write opt-in. Does not activate the child theme',
            'input_schema'       => [
                'type'       => 'object',
                'properties' => [
                    'slug'   => [ 'type' => 'string', 'description' => 'Directory slug for the child theme; defaults to {parent}-child. Sanitized to a safe key, confined to the themes directory' ],
                    'name'   => [ 'type' => 'string', 'description' => 'Human-readable theme Name header; defaults to "{Parent Name} Child"' ],
                    'parent' => [ 'type' => 'string', 'description' => 'Stylesheet directory of an installed parent theme; defaults to the active theme\'s template. Must not itself be a child theme' ],
                ],
            ],
            'validate'           => static fn (array $args): ?array => self::plan_scaffold($args)['error'] ?? null,
            'handler'            => static function (array $args): array {
                $plan = self::plan_scaffold($args);
                if (isset($plan['error'])) {
                    throw new Operation_Refused(
                        (string) $plan['error']['code'],
                        (string) $plan['error']['message'],
                        (array) ($plan['error']['data'] ?? [])
                    );
                }
                return self::write_scaffold($plan);
            },
        ];
    }

    // -------------------------------------------------------------- scaffolder

    /**
     * Resolve and vet everything the scaffolder needs from the args, with no
     * side effects, so both validate() and the handler agree on the outcome.
     *
     * @param  array<string,mixed> $args
     * @return array<string,mixed> ['error' => [...]] or the resolved plan.
     */
    private static function plan_scaffold(array $args): array
    {
        $refuse = static fn (string $code, string $message, array $data = []): array
            => [ 'error' => [ 'code' => $code, 'message' => $message, 'data' => $data ] ];

        $gate = self::file_writes_allowed();
        if (is_wp_error($gate)) {
            return $refuse((string) $gate->get_error_code(), (string) $gate->get_error_message());
        }

        // Parent: the active template by default, or an explicitly named
        // installed theme. Refuse only when the chosen parent is ITSELF a
        // child, which is the actual grandchild condition; hard-refusing
        // whenever any child is active would brick the tool the moment the
        // user activates the child they just made.
        $requested = sanitize_key((string) ($args['parent'] ?? ''));
        if ('' !== $requested) {
            $candidate = wp_get_theme($requested);
            if (! $candidate->exists()) {
                return $refuse('unknown_parent', sprintf('No installed theme with stylesheet "%s".', $requested), [ 'parent' => $requested ]);
            }
            if ($candidate->parent()) {
                return $refuse('grandchild_refused', sprintf('Theme "%s" is itself a child theme; creating a grandchild theme is not supported.', $requested), [ 'parent' => $requested ]);
            }
            $parent_slug = $requested;
        } else {
            if (is_child_theme()) {
                return $refuse(
                    'grandchild_refused',
                    'The active theme is already a child theme; creating a grandchild theme is not supported. Pass an explicit parent to scaffold a child of a different installed parent theme.',
                    [ 'stylesheet' => get_stylesheet(), 'template' => get_template() ]
                );
            }
            $parent_slug = get_template();
        }

        $slug = sanitize_key((string) ($args['slug'] ?? ($parent_slug . '-child')));
        if ('' === $slug || $slug === $parent_slug) {
            return $refuse('invalid_slug', 'Child theme slug is empty or collides with the parent theme slug after sanitization.', [ 'slug' => $slug ]);
        }

        // Path confinement: sanitize_key() already leaves a single token with
        // no slashes or dots, and resolve_path() re-proves the result cannot
        // leave the theme root (symlinked leaf included).
        $root = get_theme_root();
        $dir  = Filesystem_Guard::resolve_path($slug, $root);
        if (is_wp_error($dir)) {
            return $refuse('invalid_slug', (string) $dir->get_error_message(), [ 'slug' => $slug ]);
        }

        $existing = false;
        if (is_dir($dir)) {
            $style = @file_get_contents($dir . '/style.css');
            if (! is_string($style) || false === strpos($style, self::SCAFFOLD_MARKER)) {
                return $refuse('directory_exists', sprintf('Theme directory "%s" already exists and was not scaffolded by wpmcp; refusing to touch it.', $slug), [ 'slug' => $slug ]);
            }
            $theme = wp_get_theme($slug);
            if ($theme->exists() && $theme->get('Template') !== $parent_slug) {
                return $refuse(
                    'parent_mismatch',
                    sprintf('Existing scaffold "%s" is a child of "%s", not of "%s".', $slug, (string) $theme->get('Template'), $parent_slug),
                    [ 'slug' => $slug, 'template' => (string) $theme->get('Template'), 'expected' => $parent_slug ]
                );
            }
            // A marker-bearing directory is only "already done" when BOTH
            // files are there; a half-written scaffold is completed instead
            // of being reported as an activatable theme.
            $existing = is_file($dir . '/functions.php') && is_file($dir . '/style.css');
        }

        $parent = wp_get_theme($parent_slug);
        $name   = trim((string) ($args['name'] ?? '')) !== ''
            ? (string) $args['name']
            : $parent->get('Name') . ' Child';

        return [
            'slug'        => $slug,
            'dir'         => $dir,
            'parent'      => $parent_slug,
            'parent_name' => (string) $parent->get('Name'),
            'name'        => $name,
            'existing'    => $existing,
        ];
    }

    /**
     * Perform the vetted scaffold. functions.php is written FIRST and the
     * marker-bearing style.css LAST, and a failure removes whatever was
     * created, so a partial write can never leave a marker that makes later
     * runs report a half-theme as done.
     *
     * @param  array<string,mixed> $plan
     * @return array<string,mixed>
     */
    private static function write_scaffold(array $plan): array
    {
        $dir = (string) $plan['dir'];

        if (true === $plan['existing']) {
            return [
                'created'    => false,
                'existing'   => true,
                'stylesheet' => $plan['slug'],
                'template'   => $plan['parent'],
                'path'       => $dir,
            ];
        }

        $fresh = ! is_dir($dir);
        if ($fresh && ! wp_mkdir_p($dir)) {
            throw new Operation_Refused('mkdir_failed', 'Could not create the child theme directory.', [ 'path' => $dir ]);
        }

        $functions = "<?php\n"
            . '// ' . self::SCAFFOLD_MARKER . ".\n"
            . "add_action('wp_enqueue_scripts', function () {\n"
            . "    wp_enqueue_style('wpmcp-child-parent-style', get_template_directory_uri() . '/style.css', [], wp_get_theme(get_template())->get('Version'));\n"
            . "});\n";

        $style = "/*\n"
            . 'Theme Name: ' . self::css_comment_safe((string) $plan['name']) . "\n"
            . 'Template: ' . $plan['parent'] . "\n"
            . 'Version: 1.0.0' . "\n"
            . 'Description: Child theme of ' . self::css_comment_safe((string) $plan['parent_name']) . '. ' . self::SCAFFOLD_MARKER . ".\n"
            . "*/\n";

        // functions.php first, style.css (the idempotency marker) last.
        if (
            false === @file_put_contents($dir . '/functions.php', $functions)
            || false === @file_put_contents($dir . '/style.css', $style)
        ) {
            self::clean_partial_scaffold($dir, $fresh);
            throw new Operation_Refused('write_failed', 'Could not write the child theme files; the partial scaffold was removed.', [ 'path' => $dir ]);
        }

        // Without this the new directory is absent from the cached
        // theme_roots transient and wp_get_themes(), so the child does not
        // show up under Appearance -> Themes and is not activatable.
        wp_clean_themes_cache();

        Filesystem_Guard::log('create-child-theme', Filesystem_Guard::to_relative($dir));

        return [
            'created'    => true,
            'existing'   => false,
            'stylesheet' => $plan['slug'],
            'name'       => $plan['name'],
            'template'   => $plan['parent'],
            'path'       => $dir,
            'activated'  => false,
        ];
    }

    /** Remove a failed scaffold's files, and the directory itself when we made it. */
    private static function clean_partial_scaffold(string $dir, bool $created_dir): void
    {
        foreach ([ 'style.css', 'functions.php' ] as $file) {
            if (is_file($dir . '/' . $file)) {
                @unlink($dir . '/' . $file);
            }
        }
        if ($created_dir && is_dir($dir)) {
            @rmdir($dir);
        }
    }

    /**
     * Gate file creation the way every other write path in the repo does:
     * edit_files plus DISALLOW_FILE_EDIT. The extra filter exists so tests
     * (and a site that wants a harder no) can force the refusal without
     * redefining a constant.
     *
     * @return true|\WP_Error
     */
    private static function file_writes_allowed()
    {
        /** Filter: force theme file writes off without defining DISALLOW_FILE_EDIT. */
        if ((bool) apply_filters('wpmcp_theme_file_edit_disallowed', false)) {
            return new \WP_Error('file_edit_disabled', 'File editing is disabled on this site.');
        }
        return Filesystem_Guard::writes_allowed();
    }

    /**
     * Make a caller-supplied string safe inside a /* ... *&#47; block: no
     * newlines (which would forge extra theme headers) and no comment
     * terminator (which would end the block and append attacker CSS to a
     * stylesheet served to every visitor).
     */
    private static function css_comment_safe(string $value): string
    {
        $value = str_replace([ "\r", "\n", '*/', '/*' ], ' ', $value);
        $value = trim(preg_replace('/\s+/', ' ', $value) ?? '');
        return '' === $value ? 'Child Theme' : mb_substr($value, 0, 120);
    }

    // ---------------------------------------------------------- framework pack

    /**
     * Astra settings pack. Registered only while Astra (or an Astra child) is
     * the active family; writes are snapshotted on the astra-settings option
     * and refresh Astra's compiled CSS cache.
     *
     * @return array<string,array<string,mixed>>
     */
    private function astra_pack(): array
    {
        $allowlist = static function (): array {
            /** Filter: framework pack setting keys, keyed by family. */
            $keys = (array) apply_filters('wpmcp_theme_framework_pack_allowlist', self::ASTRA_SETTINGS, 'astra');
            return $keys;
        };

        return [
            'get-astra-settings' => [
                'mode'         => 'read',
                'capability'   => 'edit_theme_options',
                'description'  => 'Read the writable Astra theme settings (colors and content width) from the astra-settings option, with the effective per-key allowlist',
                'input_schema' => [ 'type' => 'object', 'properties' => [] ],
                'handler'      => static function () use ($allowlist): array {
                    $stored   = (array) get_option('astra-settings', []);
                    $keys     = $allowlist();
                    $settings = [];
                    foreach (array_keys($keys) as $key) {
                        $settings[ (string) $key ] = $stored[ (string) $key ] ?? null;
                    }
                    return [ 'framework' => 'astra', 'settings' => $settings, 'allowlist' => array_keys($keys) ];
                },
            ],
            'set-astra-settings' => [
                'mode'               => 'write',
                'capability'         => 'edit_theme_options',
                'enabled_by_default' => self::writes_enabled(),
                'description'        => 'Set allowlisted Astra theme settings (colors as hex/rgba, site-content-width as pixels). Values are sanitized per key, the whole batch is rejected before any write if one is invalid, the astra-settings option is snapshotted for rollback-operation, and Astra\'s compiled CSS cache is refreshed afterwards',
                'input_schema'       => [
                    'type'       => 'object',
                    'properties' => [
                        'settings' => [
                            'type'                 => 'object',
                            'minProperties'        => 1,
                            'additionalProperties' => [ 'type' => [ 'string', 'integer', 'number' ] ],
                        ],
                    ],
                    'required'   => [ 'settings' ],
                ],
                'validate'           => static function (array $args) use ($allowlist): ?array {
                    $keys = $allowlist();
                    foreach ((array) ($args['settings'] ?? []) as $key => $value) {
                        $key = (string) $key;
                        if (! isset($keys[ $key ])) {
                            return [
                                'code'    => 'key_not_allowlisted',
                                'message' => sprintf('Astra setting "%s" is not on the write allowlist.', $key),
                                'data'    => [ 'key' => $key, 'allowlist' => array_keys($keys) ],
                            ];
                        }
                        if (null === self::sanitize_pack_value((string) $keys[ $key ], $value)) {
                            return [
                                'code'    => 'invalid_setting_value',
                                'message' => sprintf('Value for Astra setting "%s" is not valid for that key.', $key),
                                'data'    => [ 'key' => $key ],
                            ];
                        }
                    }
                    return null;
                },
                'handler'            => static function (array $args) use ($allowlist): array {
                    $keys    = $allowlist();
                    $stored  = (array) get_option('astra-settings', []);
                    $written = [];
                    foreach ((array) $args['settings'] as $key => $value) {
                        $key   = (string) $key;
                        $clean = self::sanitize_pack_value((string) ($keys[ $key ] ?? ''), $value);
                        if (null === $clean) {
                            throw new Operation_Refused('invalid_setting_value', sprintf('Value for Astra setting "%s" is not valid.', $key), [ 'key' => $key ]);
                        }
                        $stored[ $key ] = $clean;
                        $written[ $key ] = $clean;
                    }
                    update_option('astra-settings', $stored);
                    self::refresh_framework_cache('astra');
                    return [ 'framework' => 'astra', 'settings' => $written ];
                },
                'snapshot'           => static fn (array $args) => [
                    'object_type' => 'option',
                    'object_id'   => 'astra-settings',
                ],
            ],
        ];
    }

    /**
     * Drop a framework's compiled CSS cache after a settings write, so the
     * change is visible on the next request instead of after the cache
     * expires. Astra's own invalidation entry point is used when present.
     */
    private static function refresh_framework_cache(string $family): void
    {
        if ('astra' === $family && method_exists('\Astra_Cache_Base', 'refresh_assets')) {
            \Astra_Cache_Base::refresh_assets('astra');
        }
        /** Action: a site or add-on refreshes its own caches after a framework pack write. */
        do_action('wpmcp_theme_framework_cache_refresh', $family);
    }

    // ------------------------------------------------------------- sanitizers

    /**
     * Sanitize one theme-mod value for its key. Returns null when the value
     * cannot be made safe, which is a refusal, never a coerced write.
     *
     * @param  mixed $value
     * @return mixed|null
     */
    private static function sanitize_mod(string $key, $value)
    {
        $rule = self::MOD_SANITIZERS[ $key ] ?? null;
        if (null === $rule) {
            /** Filter: sanitizer rule for a theme-mod key added via wpmcp_theme_mod_allowlist. */
            $rule = (string) apply_filters('wpmcp_theme_mod_sanitizer', '', $key);
            if ('' === $rule) {
                return null;
            }
        }
        if (is_array($value) || is_object($value)) {
            return null;
        }

        switch ($rule) {
            case 'attachment_id':
                $id = absint($value);
                return $id > 0 ? $id : null;
            case 'hex':
            case 'hex_or_blank':
                if ('hex_or_blank' === $rule && 'blank' === $value) {
                    // The header-text toggle core encodes as a color value.
                    return 'blank';
                }
                $hex = sanitize_hex_color_no_hash(is_string($value) ? $value : (string) $value);
                // Lowercased so a read-back is byte-stable regardless of how
                // the caller cased the input.
                return ('' === $hex || null === $hex) ? null : strtolower($hex);
            case 'url':
                $url = esc_url_raw((string) $value);
                return '' === $url ? null : $url;
            case 'header_image':
                if ('remove-header' === $value) {
                    return 'remove-header';
                }
                $url = esc_url_raw((string) $value);
                return '' === $url ? null : $url;
            default:
                $enum = self::MOD_ENUMS[ $rule ] ?? null;
                if (null === $enum) {
                    return null;
                }
                return in_array((string) $value, $enum, true) ? (string) $value : null;
        }
    }

    /**
     * Sanitize a framework-pack setting value.
     *
     * @param  mixed $value
     * @return mixed|null
     */
    private static function sanitize_pack_value(string $rule, $value)
    {
        if (is_array($value) || is_object($value)) {
            return null;
        }
        if ('color' === $rule) {
            $raw = trim((string) $value);
            $hex = sanitize_hex_color($raw);
            if (is_string($hex) && '' !== $hex) {
                return $hex;
            }
            return 1 === preg_match('/^rgba?\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*(,\s*(0|1|0?\.\d+)\s*)?\)$/', $raw)
                ? $raw
                : null;
        }
        if ('width' === $rule) {
            $px = absint($value);
            return ($px >= 300 && $px <= 3000) ? $px : null;
        }
        return null;
    }

    /** @return array<int,string> the effective allowlist, never containing structural keys. */
    private static function allowlist(): array
    {
        /** Filter: the writable theme-mod key allowlist. Structural keys are stripped regardless. */
        $keys = (array) apply_filters('wpmcp_theme_mod_allowlist', array_keys(self::MOD_SANITIZERS));
        return array_values(array_diff(array_map('strval', $keys), self::MOD_STRUCTURAL));
    }

    /** @return string framework family label ('none' when unrecognized). */
    private static function detect_framework(): string
    {
        /** Filter: theme slug (or slug prefix) to framework family map. */
        $map      = (array) apply_filters('wpmcp_theme_framework_map', self::FRAMEWORK_MAP);
        $template = strtolower(get_template());
        foreach ($map as $slug => $family) {
            $slug = strtolower((string) $slug);
            if ($template === $slug || 0 === strpos($template, $slug . '-')) {
                return (string) $family;
            }
        }
        return 'none';
    }
}
