<?php

/**
 * Registered-ability manifest — the drift guard for the plugin's MCP surface.
 *
 * GENERATED FILE: do not hand-edit. Regenerate deliberately with
 * `composer manifest:regenerate` after intentionally adding, removing,
 * renaming, or re-tiering an ability, and commit the diff.
 * Asserted by tests/free/Platform/AbilityManifestTest.php.
 *
 * Pins the canonical test environment: single-site WordPress with the
 * optional test plugins from bin/install-test-plugins.sh present (parts of
 * the registration path are conditional on ACF / SEO / i18n plugins and on
 * multisite), which is exactly the environment CI runs.
 */

return [
    'total'     => 170,
    'free'      => 155,
    'pro'       => 15,
    'abilities' => [
        'wpmcp/activate-plugin' => 'free',
        'wpmcp/add-block' => 'free',
        'wpmcp/add-menu-item' => 'free',
        'wpmcp/add-order-note' => 'free',
        'wpmcp/add-widget' => 'pro',
        'wpmcp/analyze-accessibility' => 'pro',
        'wpmcp/analyze-performance' => 'free',
        'wpmcp/analyze-seo' => 'pro',
        'wpmcp/assign-menu-to-location' => 'free',
        'wpmcp/build-page' => 'free',
        'wpmcp/call-rest' => 'free',
        'wpmcp/call-tool' => 'free',
        'wpmcp/cancel-backup-job' => 'free',
        'wpmcp/check-contrast' => 'pro',
        'wpmcp/clear-cache' => 'free',
        'wpmcp/convert-html-to-blocks' => 'free',
        'wpmcp/create-identity' => 'free',
        'wpmcp/create-menu' => 'free',
        'wpmcp/create-post' => 'free',
        'wpmcp/create-product' => 'free',
        'wpmcp/create-user' => 'free',
        'wpmcp/deactivate-plugin' => 'free',
        'wpmcp/delete-comment' => 'free',
        'wpmcp/delete-file' => 'free',
        'wpmcp/delete-identity' => 'free',
        'wpmcp/delete-media' => 'free',
        'wpmcp/delete-menu' => 'free',
        'wpmcp/delete-plugin' => 'free',
        'wpmcp/delete-post' => 'free',
        'wpmcp/delete-product' => 'free',
        'wpmcp/delete-rows' => 'free',
        'wpmcp/delete-theme' => 'free',
        'wpmcp/delete-transient' => 'free',
        'wpmcp/describe-table' => 'free',
        'wpmcp/detect-builder' => 'pro',
        'wpmcp/disable-maintenance' => 'free',
        'wpmcp/duplicate-block' => 'free',
        'wpmcp/edit-comment' => 'free',
        'wpmcp/edit-file' => 'free',
        'wpmcp/enable-maintenance' => 'free',
        'wpmcp/export-content' => 'free',
        'wpmcp/extract-content' => 'pro',
        'wpmcp/find-orphan-posts' => 'free',
        'wpmcp/generate-widget' => 'pro',
        'wpmcp/get-analytics-connection-status' => 'free',
        'wpmcp/get-analytics-summary' => 'free',
        'wpmcp/get-backup-status' => 'free',
        'wpmcp/get-block-type' => 'free',
        'wpmcp/get-builder-content' => 'pro',
        'wpmcp/get-cache-status' => 'free',
        'wpmcp/get-comment' => 'free',
        'wpmcp/get-connection-info' => 'free',
        'wpmcp/get-debug-config' => 'free',
        'wpmcp/get-debug-log' => 'free',
        'wpmcp/get-elementor-data' => 'pro',
        'wpmcp/get-fields' => 'free',
        'wpmcp/get-governance-settings' => 'free',
        'wpmcp/get-link-map' => 'free',
        'wpmcp/get-maintenance-status' => 'free',
        'wpmcp/get-media' => 'free',
        'wpmcp/get-menu' => 'free',
        'wpmcp/get-option' => 'free',
        'wpmcp/get-order' => 'free',
        'wpmcp/get-page' => 'free',
        'wpmcp/get-plugin-info' => 'free',
        'wpmcp/get-post' => 'free',
        'wpmcp/get-post-meta' => 'free',
        'wpmcp/get-post-translations' => 'free',
        'wpmcp/get-product' => 'free',
        'wpmcp/get-revision' => 'free',
        'wpmcp/get-sales-report' => 'free',
        'wpmcp/get-search-console-queries' => 'free',
        'wpmcp/get-search-console-summary' => 'free',
        'wpmcp/get-seo-meta' => 'free',
        'wpmcp/get-seo-status' => 'free',
        'wpmcp/get-settings' => 'free',
        'wpmcp/get-site-context' => 'free',
        'wpmcp/get-tool-schema' => 'free',
        'wpmcp/get-top-pages' => 'free',
        'wpmcp/get-user' => 'free',
        'wpmcp/get-widget-schema' => 'free',
        'wpmcp/import-content' => 'free',
        'wpmcp/insert-pattern' => 'free',
        'wpmcp/insert-row' => 'free',
        'wpmcp/install-plugin' => 'free',
        'wpmcp/install-theme' => 'free',
        'wpmcp/is-multisite' => 'free',
        'wpmcp/link-post-translations' => 'free',
        'wpmcp/list-backup-jobs' => 'free',
        'wpmcp/list-block-types' => 'free',
        'wpmcp/list-comments' => 'free',
        'wpmcp/list-cron-events' => 'free',
        'wpmcp/list-directory' => 'free',
        'wpmcp/list-exports' => 'free',
        'wpmcp/list-field-groups' => 'free',
        'wpmcp/list-governance-audit-log' => 'free',
        'wpmcp/list-identities' => 'free',
        'wpmcp/list-languages' => 'free',
        'wpmcp/list-menu-locations' => 'free',
        'wpmcp/list-menus' => 'free',
        'wpmcp/list-operations' => 'free',
        'wpmcp/list-orders' => 'free',
        'wpmcp/list-patterns' => 'free',
        'wpmcp/list-plugins' => 'free',
        'wpmcp/list-post-types' => 'free',
        'wpmcp/list-posts' => 'free',
        'wpmcp/list-product-categories' => 'free',
        'wpmcp/list-products' => 'free',
        'wpmcp/list-rest-routes' => 'free',
        'wpmcp/list-revisions' => 'free',
        'wpmcp/list-shortcodes' => 'free',
        'wpmcp/list-sidebar-widgets' => 'free',
        'wpmcp/list-sidebars' => 'free',
        'wpmcp/list-tables' => 'free',
        'wpmcp/list-taxonomies' => 'free',
        'wpmcp/list-themes' => 'free',
        'wpmcp/list-tool-catalog' => 'free',
        'wpmcp/list-tools' => 'free',
        'wpmcp/list-transients' => 'free',
        'wpmcp/list-users' => 'free',
        'wpmcp/list-widgets' => 'free',
        'wpmcp/moderate-comment' => 'free',
        'wpmcp/move-block' => 'free',
        'wpmcp/move-element' => 'pro',
        'wpmcp/parse-blocks' => 'free',
        'wpmcp/query' => 'free',
        'wpmcp/read-file' => 'free',
        'wpmcp/remove-block' => 'free',
        'wpmcp/remove-element' => 'pro',
        'wpmcp/remove-menu-item' => 'free',
        'wpmcp/render-shortcode' => 'free',
        'wpmcp/restore-revision' => 'free',
        'wpmcp/rollback-operation' => 'free',
        'wpmcp/rollback-session' => 'free',
        'wpmcp/run-event' => 'free',
        'wpmcp/run-php-snippet' => 'pro',
        'wpmcp/run-wp-cli' => 'pro',
        'wpmcp/scan-security' => 'free',
        'wpmcp/schedule-event' => 'free',
        'wpmcp/search-files' => 'free',
        'wpmcp/search-plugins' => 'free',
        'wpmcp/serialize-blocks' => 'free',
        'wpmcp/set-post-language' => 'free',
        'wpmcp/set-post-meta' => 'free',
        'wpmcp/set-post-terms' => 'free',
        'wpmcp/sideload-image' => 'free',
        'wpmcp/suggest-internal-links' => 'free',
        'wpmcp/switch-theme' => 'free',
        'wpmcp/trigger-backup' => 'free',
        'wpmcp/unschedule-event' => 'free',
        'wpmcp/update-block' => 'free',
        'wpmcp/update-blocks' => 'free',
        'wpmcp/update-builder-content' => 'pro',
        'wpmcp/update-element' => 'pro',
        'wpmcp/update-fields' => 'free',
        'wpmcp/update-governance-settings' => 'free',
        'wpmcp/update-media' => 'free',
        'wpmcp/update-menu-item' => 'free',
        'wpmcp/update-option' => 'free',
        'wpmcp/update-order-status' => 'free',
        'wpmcp/update-plugin' => 'free',
        'wpmcp/update-post' => 'free',
        'wpmcp/update-product' => 'free',
        'wpmcp/update-rows' => 'free',
        'wpmcp/update-seo-meta' => 'free',
        'wpmcp/update-settings' => 'free',
        'wpmcp/update-theme' => 'free',
        'wpmcp/update-user' => 'free',
        'wpmcp/validate-php-snippet' => 'free',
        'wpmcp/write-file' => 'free',
    ],
];
