<?php

namespace WPMCP\Tools\Builders;

if (! defined('ABSPATH')) {
    exit;
}

/**
 * Read/write access to a classic Oxygen (4.x and earlier) page.
 *
 * Oxygen 4's save stores a page twice: the JSON tree in ct_builder_json
 * (see Oxygen_Classic_Json), and a copy of it as nested ct_* shortcodes in
 * ct_builder_shortcodes, whose ct_options attribute carries each element's
 * options as JSON and whose ct_sign_sha256 attribute signs it with the
 * site's key. It renders from the tree whenever the tree has elements and
 * falls back to the shortcodes only when it has none, so the tree is the
 * authoritative store; Oxygen before 4.0 has only the shortcodes, and a page
 * saved then and never since still holds only them. From Oxygen 4.8.3 the
 * rows sit under `_ct_` keys; earlier versions use the `ct_` keys.
 *
 * A write keeps the two stores consistent the way Oxygen's save does: it
 * first copies the old tree into Oxygen's own revision rows, then stores
 * the shortcode copy Oxygen generates from the new tree, then the tree, and
 * then refreshes the generated CSS (see Oxygen_Classic_Cache). The shortcode
 * copy is signed with the site's key, so it is only ever generated by
 * Oxygen's own serializer. That makes a write need Oxygen loaded when the
 * page has a shortcode copy; a page in the pre-4.0 format, where the signed
 * shortcodes are the only store, is read-only here. Dynamic data shortcodes
 * ([oxygen ...]) new text brings in are signed through Oxygen too, as its
 * save signs them.
 *
 * Every row is postmeta, which the post snapshot captures, so a rollback
 * restores tree, shortcode copy and revisions together as the consistent set
 * they were; the rollback path then refreshes the CSS the same way.
 */
class Oxygen_Classic_Content
{
    public const JSON_KEY = 'ct_builder_json';

    public const SHORTCODES_KEY = 'ct_builder_shortcodes';

    public static function plugin_active(): bool
    {
        return Oxygen_Classic_Cache::plugin_active();
    }

    /**
     * Whether the page's rows sit under the `_ct_` keys: what the loaded
     * Oxygen reads when it says its version, otherwise whichever layout the
     * page's rows are stored in.
     */
    public static function prefixed(int $post_id): bool
    {
        $version = Oxygen_Classic_Cache::version();
        if ('' !== $version) {
            return version_compare($version, '4.8.3', '>=');
        }

        return metadata_exists('post', $post_id, '_' . self::JSON_KEY) || metadata_exists('post', $post_id, '_' . self::SHORTCODES_KEY);
    }

    /** A layout row's key as this page stores it. */
    public static function key(int $post_id, string $base): string
    {
        return (self::prefixed($post_id) ? '_' : '') . $base;
    }

    public static function get_json(int $post_id): string
    {
        $value = get_post_meta($post_id, self::key($post_id, self::JSON_KEY), true);

        return is_string($value) ? $value : '';
    }

    public static function get_shortcodes(int $post_id): string
    {
        $value = get_post_meta($post_id, self::key($post_id, self::SHORTCODES_KEY), true);

        return is_string($value) ? $value : '';
    }

    /**
     * Which store Oxygen renders the page from: 'json' when the tree has
     * elements (and the loaded Oxygen reads trees, which it does from 4.0),
     * 'shortcodes' for a page in the older format, 'none' otherwise.
     */
    public static function format(int $post_id): string
    {
        $version      = Oxygen_Classic_Cache::version();
        $json_renders = '' === $version || version_compare($version, '4.0', '>=');

        if ($json_renders && Oxygen_Classic_Json::has_elements(self::get_json($post_id))) {
            return 'json';
        }

        return '' !== trim(self::get_shortcodes($post_id)) ? 'shortcodes' : 'none';
    }

    /** Whether Oxygen's own serializer is available to generate the signed copy. */
    public static function can_regenerate(): bool
    {
        return self::plugin_active() && function_exists('components_json_to_shortcodes') && function_exists('ct_base64_encode_decode_tree');
    }

    /** Whether a write can keep both stores consistent right now. */
    public static function writable(int $post_id): bool
    {
        return 'json' === self::format($post_id) && ('' === trim(self::get_shortcodes($post_id)) || self::can_regenerate());
    }

    /** @return array<string,mixed> */
    public static function read(int $post_id): array
    {
        $format  = self::format($post_id);
        $content = 'json' === $format ? self::get_json($post_id) : self::get_shortcodes($post_id);

        try {
            $tree  = 'json' === $format ? Oxygen_Classic_Json::tree($content) : self::legacy_tree($content);
            $error = null;
        } catch (\InvalidArgumentException $e) {
            $tree  = [];
            $error = $e->getMessage();
        }

        $out = [
            'post_id'       => $post_id,
            'builder'       => 'oxygen-classic',
            'plugin_active' => self::plugin_active(),
            'format'        => $format,
            'writable'      => self::writable($post_id),
            'tree'          => $tree,
            'content'       => $content,
        ];
        if (null !== $error) {
            $out['tree_error'] = $error;
        }

        return $out;
    }

    /**
     * The filter every fragment a write adds goes through: a dynamic data
     * shortcode ([oxygen ...]) that is not signed yet is signed by Oxygen,
     * the way its save signs them, or refused when Oxygen is not loaded.
     * Signed ones are left as they are.
     */
    public static function signer(): callable
    {
        return static function (string $fragment): string {
            return (string) preg_replace_callback(
                '/\[oxygen ([^\]]*)\]/i',
                static function (array $match): string {
                    if (false !== stripos($match[0], 'ct_sign_sha256=')) {
                        return $match[0];
                    }
                    if (! self::plugin_active() || ! function_exists('ct_sign_oxy_dynamic_shortcode')) {
                        throw new \InvalidArgumentException(esc_html('Oxygen signs its dynamic data shortcodes ([oxygen ...]) with the site\'s key; activate Oxygen to add them.'));
                    }

                    return (string) ct_sign_oxy_dynamic_shortcode($match);
                },
                $fragment
            );
        };
    }

    /**
     * The shortcode copy to store with a new tree: generated by Oxygen when
     * it is loaded, exactly as its save generates it (code fields encoded
     * through its tree helper, then its serializer, which signs each
     * element); null when Oxygen is not loaded, which a caller only reaches
     * for a page that has no copy.
     */
    public static function shortcodes_for(string $json): ?string
    {
        if (! self::can_regenerate()) {
            return null;
        }

        // The serializer signs through this global, which Oxygen creates
        // when it loads; set it up the same way if something cleared it.
        global $oxygen_signature;
        if (! is_object($oxygen_signature) && class_exists('OXYGEN_VSB_Signature')) {
            $oxygen_signature = new \OXYGEN_VSB_Signature(); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Oxygen's own signer, created the way Oxygen creates it on load.
        }

        $tree = json_decode($json, true);
        try {
            if (is_array($tree) && isset($tree['children'])) {
                $tree['children'] = ct_base64_encode_decode_tree($tree['children']);
            }
            $out = components_json_to_shortcodes((string) wp_json_encode($tree));
        } catch (\Throwable $e) {
            throw new \RuntimeException(esc_html('Oxygen could not generate the shortcode copy of this tree: ' . $e->getMessage()));
        }
        if (! is_string($out)) {
            throw new \RuntimeException(esc_html('Oxygen could not generate the shortcode copy of this tree.'));
        }

        return $out;
    }

    /**
     * Store a new tree, and its shortcode copy when there is one, the way
     * Oxygen's save does, then refresh the page's CSS. A write that changes
     * nothing touches nothing.
     */
    public static function save(int $post_id, string $json, ?string $shortcodes): void
    {
        $json_key = self::key($post_id, self::JSON_KEY);
        if (get_post_meta($post_id, $json_key, true) === $json) {
            return;
        }
        $shortcodes_key = self::key($post_id, self::SHORTCODES_KEY);

        if (self::plugin_active() && class_exists('Oxygen_Revisions') && method_exists('Oxygen_Revisions', 'create_revision')) {
            try {
                \Oxygen_Revisions::create_revision($post_id);
            } catch (\Throwable $e) {
                // A missing revision must never fail the write.
                unset($e);
            }
        }

        if (null !== $shortcodes) {
            // Oxygen's save passes the copy to update_post_meta() as it is,
            // not slashed first, so the row holds it unslashed; the same
            // call stores the same row.
            update_post_meta($post_id, $shortcodes_key, $shortcodes);
        }
        update_post_meta($post_id, $json_key, wp_slash($json));

        Oxygen_Classic_Cache::refresh($post_id);
    }

    /**
     * The path tree of a page in the pre-4.0 format, read from its
     * shortcodes: the tag less the depth suffix Oxygen adds to nested
     * containers (ct_div_block_2), the options from ct_options, and the text
     * of an element that has any.
     */
    public static function legacy_tree(string $shortcodes): array
    {
        return self::legacy_nodes(WPBakery_Shortcodes::tree($shortcodes));
    }

    private static function legacy_nodes(array $nodes): array
    {
        $out = [];
        foreach ($nodes as $node) {
            $name = (string) $node['tag'];
            if (preg_match('/^(.+)_\d+$/', $name, $m) && in_array($m[1], Oxygen_Classic_Json::CONTAINERS, true)) {
                $name = $m[1];
            }
            $options = json_decode((string) ($node['attrs']['ct_options'] ?? ''), true);
            $options = is_array($options) ? $options : [];

            $item = [
                'path'    => $node['path'],
                'id'      => is_int($options['ct_id'] ?? null) ? $options['ct_id'] : null,
                'name'    => $name,
                'options' => $options,
            ];
            if (array_key_exists('text', $node)) {
                $item['text'] = $node['text'];
            }
            if (array_key_exists('children', $node)) {
                $item['children'] = self::legacy_nodes($node['children']);
            }
            $out[] = $item;
        }

        return $out;
    }
}
