<?php
/**
 * Plugin Name: WP MCP - MCP Server with Snapshot Undo for AI Agents
 * Plugin URI: https://wpmcp-pro.com/
 * Description: Connect an AI agent to this site over the Model Context Protocol. Every write takes a snapshot first, so any change can be rolled back.
 * Version: {{VERSION}}
 * Requires at least: 6.9
 * Tested up to: 7.1
 * Requires PHP: 8.1
 * Author: Fahad Murtaza
 * Author URI: https://wpmcp-pro.com/
 * License: GPL-2.0-or-later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: wpmcp
 * Domain Path: /languages
 *
 * The WordPress.org build. No licensing SDK, no paid predicate, no quota that
 * a payment lifts and no execution construct: the paid tier is a separate
 * add-on plugin distributed off-directory, which is the shape guideline 5
 * recommends ("add-on plugins, hosted outside of WordPress.org, in order to
 * exclude the premium code"). Generated by scripts/build-wporg-release.sh.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
define( 'WPMCP_VERSION', '{{VERSION}}' );
define( 'WPMCP_FILE', __FILE__ );
define( 'WPMCP_DIR', plugin_dir_path( __FILE__ ) );
require_once __DIR__ . '/vendor/autoload.php';
\WPMCP\Plugin::instance()->boot();
